spring.application.name=StudentManagement
server.port=${PORT:8080}

# 1. Chỉ chứa địa chỉ Server và Database (KHÔNG để mật khẩu ở đây)
spring.datasource.url=jdbc:postgresql://ep-nameless-term-a1xvcgzf-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

# 2. Tách Username và Password ra riêng biệt 
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2ad3CIuiyJEr

# 3. Các cấu hình quan trọng khác 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect